### ISSUE TITLE
Handle incompatibilities between MediaWiki API versions

### ISSUE THREAD

**Issue by blackwinter** [jpatokal/mediawiki-gateway#76]
Watch mediawiki-api-announce-l for breaking changes that impact the library and make necessary updates within a few weeks.

**Comment by jpatokal** [comment]
Yup, I think to lock this library to the old API, give up on new development and point users to the official Ruby client (and I've updated the docs accordingly).  The official Ruby client is not quite feature-complete yet, but it's a matter of time.
